= Lab - Deploying a .NET Core Application

[abstract]
--
In this lab we will push a .NET Core web application to cloud foundry.
--

= Lab - From Zero to Pushing Your First Application

== Target

. If you haven't already, download the latest release of the Cloud Foundry command line interface  (CLI) from https://github.com/cloudfoundry/cli/releases for your operating system and install it.

. Set the API target for the CLI: (set appropriate end point for your environment)
+
----
$ cf api https://api.sys.azure.rick-ross.com --skip-ssl-validation
----

. Login to Pivotal Cloudfoundry:
+
----
$ cf login
----
+
Follow the prompts.  You should have a welcome card with your username and password on it.  If you didn't get one, please ask.

== Install .NET Core

. Download .NET Core from link:https://www.microsoft.com/net/core for your operating system
. Note that you might need to open a new shell/termina/command window to run the donet core commands

== Prepare Application

. Restore the .NET Dependencies
+
----
$ dotnet restore
----

. Run it locally 
+
----
$ dotnet run
----
Note the URL that the application is running on
+
====
----
Project pcf-dotnet-core-simple-aspnet (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hosting environment: Production
Content root path: C:\Users\Rick Ross\pcf-dotnet-core-simple-aspnet\bin\Debug\netcoreapp1.0
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
---

. Visit the application in your browser by hitting the URL (e.g. http://localhost:5000)

 
== Push It!

. Change to the _ViewEnvironment_ application directory (this is the folder containing the code files and manifest.yml):
+
----
$ cd $BOOTCAMP_HOME/pcf-dotnet-core-simple-aspnet
----


== Push It!

. Push the application!
+
----
$ cf push
----
+
You should see output similar to the following listing. Take a look at the listing callouts for a play-by-play of what's happening:
+
====